spring.application.name=MindConnect

//SQL-Informartion
spring.datasource.url=jdbc:mysql://localhost:3306/mindconnectusers
spring.datasource.username=root
spring.datasource.password=Eldelanasa88!!
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

//JWT-configuration
app.jwt-secret=sWyQxG9p82p9P/h1F/j58/wjAjkjEDkkjL1LYkPMgCpFYQJNocfmKcqp4267AMmG+BDy98EqVktu591tNx1TyYVGndplvAcF4MIBVGO8fzlPe91RxYqOwOx2LIa0Vki26PVGKI+ukTMS+NAmFaCKQZz27OjJyCqWrHcrz++FsJs/9k/hjOWrSYhBthzBfKrW8WxeBtkIgik16C/9V3KAFFZgptPjPDKfyN+O8x0pWFhGSFRM6vfjyUMz/Lys43LhHvqm03Ign27xmL0vT1HctaHeyc07blHOjMCzIAGSycyuCzMSGatgFw1kfOMc4Mpf3Ns68L/cFNJPR5QuNVH7U7xedBDERQOiIV0hrvyPgLk=
app.jwt-expiration=86400000

//JPA-config
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format-sql=true

//Email-bean
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=lennoxrr21@gmail.com
spring.mail.password=asmo wwtk orxi kjkz
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
